apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- configmap.yaml
namespace: vivasaude
images:
- name: financial-core-api-dev
  newName: diegosanteri/financial-core-api
  newTag: latest
patchesStrategicMerge:
- replicas-patch.yaml
