---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: financial-core-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-core-api-deployment
  targetCPUUtilizationPercentage: 50