---
apiVersion: v1
kind: Service
metadata:
  name: financial-core-api-service
  labels:
    app: financial-core-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: financial-core-api